### ISSUE TITLE
Long topic titles and user names appear garbled on mobile device

### ISSUE THREAD

**Issue by useffc** [twinlabs/forum#171]
I've only tested this on iOS Safari, but long topic titles and user names are garbled on narrow width viewports. Screenshot attached at bottom.

This is almost certainly because ```text-overflow``` is set to ```ellipsis``` for these elements.

![img_1790](https://cloud.githubusercontent.com/assets/1919818/11016650/8e039066-8556-11e5-9293-ae6f8588c43f.PNG)

**Comment by useffc** [comment]
I think that a good way to resolve this would be to limit the number of characters for each thread and user depending on the device width rather than use text-overflow ellipsis.

**Comment by nchase** [comment]
interesting. this seems like a rendering bug in safari - I agree that we should work around it, but is there any evidence on the web of other people having this issue?

**Comment by nchase** [comment]
1. I agree that we should kill `text-overflow: ellipsis` in indexpage atom metadata for now.
2. "limit the number of characters for each thread and user depending on the device width" – did you have implementation details in mind for this?

**Comment by nchase** [comment]
fixed in 48f8f230. the fix is just a simple compromise where we stop doing the nice overflow/ellipsis behavior.

if a user wants to have a long name or a long thread title, we won't try to deal with it gracefully, we'll just show the whole thing until we can figure out a simple, elegant, cross-platform solution.
